services:
  - type: web
    name: trapick
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r trapick/requirements.txt
      cd trapick && python manage.py collectstatic --noinput
    startCommand: cd trapick && gunicorn trapick.wsgi:application